trigger:
- main

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: pytest
  displayName: 'Run tests'